# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelpicture = QtWidgets.QLabel(self.centralwidget)
        self.labelpicture.setGeometry(QtCore.QRect(10, 0, 800, 601))
        self.labelpicture.setObjectName("labelpicture")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(830, 10, 291, 311))
        self.groupBox.setObjectName("groupBox")
        self.picturetext = QtWidgets.QTextEdit(self.groupBox)
        self.picturetext.setGeometry(QtCore.QRect(10, 10, 271, 291))
        self.picturetext.setObjectName("picturetext")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(830, 330, 291, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadingpicture = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadingpicture.setObjectName("loadingpicture")
        self.verticalLayout.addWidget(self.loadingpicture)
        self.pictureTFtextButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pictureTFtextButton.setObjectName("pictureTFtextButton")
        self.verticalLayout.addWidget(self.pictureTFtextButton)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(830, 450, 291, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 271, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.GrayButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.GrayButton.setObjectName("GrayButton")
        self.verticalLayout_2.addWidget(self.GrayButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.thresholdlineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.thresholdlineEdit.setObjectName("thresholdlineEdit")
        self.horizontalLayout.addWidget(self.thresholdlineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.thresholdButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.thresholdButton.setObjectName("thresholdButton")
        self.verticalLayout_2.addWidget(self.thresholdButton)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(2, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelpicture.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "圖片資訊"))
        self.groupBox_2.setTitle(_translate("MainWindow", "工作按鈕"))
        self.loadingpicture.setText(_translate("MainWindow", "載入圖片"))
        self.pictureTFtextButton.setText(_translate("MainWindow", "文字偵測"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.GrayButton.setText(_translate("MainWindow", "灰階化"))
        self.label.setText(_translate("MainWindow", "二質化:\n"
"(1~255)"))
        self.thresholdButton.setText(_translate("MainWindow", "二質化"))

