# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelpicture = QtWidgets.QLabel(self.centralwidget)
        self.labelpicture.setGeometry(QtCore.QRect(10, 0, 800, 601))
        self.labelpicture.setObjectName("labelpicture")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(830, 0, 291, 311))
        self.groupBox.setObjectName("groupBox")
        self.picturetext = QtWidgets.QTextEdit(self.groupBox)
        self.picturetext.setGeometry(QtCore.QRect(10, 10, 271, 291))
        self.picturetext.setObjectName("picturetext")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(830, 320, 291, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadingpicture = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadingpicture.setObjectName("loadingpicture")
        self.verticalLayout.addWidget(self.loadingpicture)
        self.pictureTFtextButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pictureTFtextButton.setObjectName("pictureTFtextButton")
        self.verticalLayout.addWidget(self.pictureTFtextButton)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(830, 420, 281, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 271, 230))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.graycheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.graycheckBox.setFont(font)
        self.graycheckBox.setObjectName("graycheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.graycheckBox)
        self.thresholdcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.thresholdcheckBox.setFont(font)
        self.thresholdcheckBox.setObjectName("thresholdcheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.thresholdcheckBox)
        self.ErosioncheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.ErosioncheckBox.setFont(font)
        self.ErosioncheckBox.setObjectName("ErosioncheckBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ErosioncheckBox)
        self.DilationcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.DilationcheckBox.setFont(font)
        self.DilationcheckBox.setObjectName("DilationcheckBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DilationcheckBox)
        self.averagingcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.averagingcheckBox.setFont(font)
        self.averagingcheckBox.setObjectName("averagingcheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.averagingcheckBox)
        self.medianBlurcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.medianBlurcheckBox.setFont(font)
        self.medianBlurcheckBox.setObjectName("medianBlurcheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.medianBlurcheckBox)
        self.GaussiacheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.GaussiacheckBox.setFont(font)
        self.GaussiacheckBox.setObjectName("GaussiacheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.GaussiacheckBox)
        self.BilateralcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.BilateralcheckBox.setFont(font)
        self.BilateralcheckBox.setObjectName("BilateralcheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.BilateralcheckBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.thresholdlineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.thresholdlineEdit.setObjectName("thresholdlineEdit")
        self.horizontalLayout.addWidget(self.thresholdlineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelpicture.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "圖片資訊"))
        self.groupBox_2.setTitle(_translate("MainWindow", "工作按鈕"))
        self.loadingpicture.setText(_translate("MainWindow", "載入圖片"))
        self.pictureTFtextButton.setText(_translate("MainWindow", "文字偵測"))
        self.groupBox_3.setTitle(_translate("MainWindow", "影像處理"))
        self.graycheckBox.setText(_translate("MainWindow", "灰階化"))
        self.thresholdcheckBox.setText(_translate("MainWindow", "二質化"))
        self.ErosioncheckBox.setText(_translate("MainWindow", "侵蝕"))
        self.DilationcheckBox.setText(_translate("MainWindow", "膨脹"))
        self.averagingcheckBox.setText(_translate("MainWindow", "平均"))
        self.medianBlurcheckBox.setText(_translate("MainWindow", "medianBlur"))
        self.GaussiacheckBox.setText(_translate("MainWindow", "高斯"))
        self.BilateralcheckBox.setText(_translate("MainWindow", "雙向濾波"))
        self.label.setText(_translate("MainWindow", "二質化:\n"
"(1~255)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

